/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/components/AboutView.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    OtroComponente: typeof import('./src/components/OtroComponente.vue')['default']
    ProductsView: typeof import('./src/components/ProductsView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoresView: typeof import('./src/components/StoresView.vue')['default']
    TargetAbout: typeof import('./src/components/TargetAbout.vue')['default']
    WorkView: typeof import('./src/components/WorkView.vue')['default']
  }
}
